pandas is  one of the most popular and widely used programming languages in the world. It is known for its simplicity, readability, and versatility, making it an excellent choice for both beginners and experienced developers.

types of pandas
sereis and dataframe

series
A series is  one dimensional labeled data

In [7]:
import pandas as pd
import numpy as np
label=['a','b','c','d']
my_list=[10,20,30,40]
arr=np.array([1,2,3,4,5,6])
d={'a':10,'b':20,'c':30,'d':40}
pd.Series(my_list )

0    10
1    20
2    30
3    40
dtype: int64

In [4]:
pd.Series(my_list,index=label)

a    10
b    20
c    30
d    40
dtype: int64

In [8]:
pd.Series(arr)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [9]:
pd.Series(d)

a    10
b    20
c    30
d    40
dtype: int64

DataFrame combined multiple series

Creating a dataframe
selection and indexing of columns
creating a new column
removing column 
selecting row 
selecting subsets of rows and column 
conditional selections

In [10]:
import pandas as pd
import numpy as np
data={
    'name':['Tom','Jerry','Mickey','Donald'],
    'age':[20,21,22,23],
    'city':['New York','Los Angeles','Chicago','Houston']  ,
    'salary':[50000,60000,70000,80000]
}

pd.DataFrame(data)

     name  age         city  salary
0     Tom   20     New York   50000
1   Jerry   21  Los Angeles   60000
2  Mickey   22      Chicago   70000
3  Donald   23      Houston   80000

In [13]:
data_list=[
    ['Tom',20,'New York',50000],['Jerry',21,'Los Angeles',60000],
    ['Mickey',22,'Chicago',70000],['Donald',23,'Houston',80000]]

df=pd.DataFrame(data_list,columns=['name','age','city','salary'])

In [14]:
df.head(5)

     name  age         city  salary
0     Tom   20     New York   50000
1   Jerry   21  Los Angeles   60000
2  Mickey   22      Chicago   70000
3  Donald   23      Houston   80000

selecting and indexing of columns

In [18]:
df['city']

0       New York
1    Los Angeles
2        Chicago
3        Houston
Name: city, dtype: object

In [19]:
df[['name','age']]

     name  age
0     Tom   20
1   Jerry   21
2  Mickey   22
3  Donald   23

creating new columns

In [20]:
df['Designation']=['Engineer','Doctor','Artist','Pilot']

In [21]:
df

     name  age         city  salary Designation
0     Tom   20     New York   50000    Engineer
1   Jerry   21  Los Angeles   60000      Doctor
2  Mickey   22      Chicago   70000      Artist
3  Donald   23      Houston   80000       Pilot

In [24]:
df.drop('Designation',axis=1,inplace=True)

In [25]:
df

     name  age         city  salary
0     Tom   20     New York   50000
1   Jerry   21  Los Angeles   60000
2  Mickey   22      Chicago   70000
3  Donald   23      Houston   80000

In [26]:
df.drop(0,axis=0)

     name  age         city  salary
1   Jerry   21  Los Angeles   60000
2  Mickey   22      Chicago   70000
3  Donald   23      Houston   80000

Selecting a rows

In [29]:
df.loc[[0,1]]

    name  age         city  salary
0    Tom   20     New York   50000
1  Jerry   21  Los Angeles   60000

selecting subsets of rows and columns

In [31]:
df.loc[[0,1],['name','age']]

    name  age
0    Tom   20
1  Jerry   21

conditional selecting

In [32]:
df[df['age']>21]

     name  age     city  salary
2  Mickey   22  Chicago   70000
3  Donald   23  Houston   80000

In [36]:
df[(df['age']>21 )& (df['city']=='Chicago')]

     name  age     city  salary
2  Mickey   22  Chicago   70000

Missing data  and finding null value

In [37]:
data={
    'A': [1, 2, np.nan, 4],
    'B': [5, np.nan, np.nan, 8],
    'C': [9, 10, 11, 12],
    'D': [np.nan, 14, 15, 16]
}

df = pd.DataFrame(data)

In [38]:
df

     A    B   C     D
0  1.0  5.0   9   NaN
1  2.0  NaN  10  14.0
2  NaN  NaN  11  15.0
3  4.0  8.0  12  16.0

In [39]:
df.isna()

       A      B      C      D
0  False  False  False   True
1  False   True  False  False
2   True   True  False  False
3  False  False  False  False

In [41]:
df.isnull().sum()

A    1
B    2
C    0
D    1
dtype: int64

removing null values

In [42]:
df.dropna()

     A    B   C     D
3  4.0  8.0  12  16.0

In [44]:
df.dropna(thresh=3)

     A    B   C     D
0  1.0  5.0   9   NaN
1  2.0  NaN  10  14.0
3  4.0  8.0  12  16.0

In [45]:
df.fillna(0)

     A    B   C     D
0  1.0  5.0   9   0.0
1  2.0  0.0  10  14.0
2  0.0  0.0  11  15.0
3  4.0  8.0  12  16.0

In [46]:
values={
    'A': 0,'B': 100,'C': 200,'D': 400}
df.fillna(value=values)

     A      B   C      D
0  1.0    5.0   9  400.0
1  2.0  100.0  10   14.0
2  0.0  100.0  11   15.0
3  4.0    8.0  12   16.0

In [47]:
df.fillna(df.mean())

          A    B   C     D
0  1.000000  5.0   9  15.0
1  2.000000  6.5  10  14.0
2  2.333333  6.5  11  15.0
3  4.000000  8.0  12  16.0

In [13]:
#datafrmae
import pandas as pd
user={
    'name':['Alice','Bob','Charlie','David'],
    'age':[25,30,35,40],
    'city':['New York','Los Angeles','Chicago','Houston'],
    'salary':[70000,80000,90000,100000]
}
df1=pd.DataFrame(user)

In [8]:
df

      name  age         city  salary
0    Alice   25     New York   70000
1      Bob   30  Los Angeles   80000
2  Charlie   35      Chicago   90000
3    David   40      Houston  100000

In [12]:
data=["jack",3,True,40,"mohan",False,50,"sita",True,60]
df

    data
0   jack
1      3
2   True
3     40
4  mohan
5  False
6     50
7   sita
8   True
9     60

In [16]:
df1[['name','age']]

      name  age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40

In [17]:
df1['designation']=['Engineer','Doctor','Artist','Pilot ']

In [18]:
df1

      name  age         city  salary designation
0    Alice   25     New York   70000    Engineer
1      Bob   30  Los Angeles   80000      Doctor
2  Charlie   35      Chicago   90000      Artist
3    David   40      Houston  100000      Pilot

In [20]:
df1.drop('designation',axis=1)

      name  age         city  salary
0    Alice   25     New York   70000
1      Bob   30  Los Angeles   80000
2  Charlie   35      Chicago   90000
3    David   40      Houston  100000

In [21]:
df1

      name  age         city  salary designation
0    Alice   25     New York   70000    Engineer
1      Bob   30  Los Angeles   80000      Doctor
2  Charlie   35      Chicago   90000      Artist
3    David   40      Houston  100000      Pilot

In [23]:
df1.drop('designation',axis=1,inplace=True)

In [24]:
df1

      name  age         city  salary
0    Alice   25     New York   70000
1      Bob   30  Los Angeles   80000
2  Charlie   35      Chicago   90000
3    David   40      Houston  100000

In [26]:
df1.loc[[0,1,2,3]]

      name  age         city  salary
0    Alice   25     New York   70000
1      Bob   30  Los Angeles   80000
2  Charlie   35      Chicago   90000
3    David   40      Houston  100000

In [28]:
#finding null values
import numpy as np
data={
    'A': [1, 2, np.nan, 4],
    'B': [5, np.nan, np.nan, 8],
    'C': [9, 10, 11, 12],
    'D': [np.nan, 14, 15, 16]
}

df2=pd.DataFrame(data)

In [31]:
df2.isna().sum()

A    1
B    2
C    0
D    1
dtype: int64

In [33]:
df2.dropna(thresh=2)

     A    B   C     D
0  1.0  5.0   9   NaN
1  2.0  NaN  10  14.0
2  NaN  NaN  11  15.0
3  4.0  8.0  12  16.0

In [34]:
df2.fillna(df2.mean())

          A    B   C     D
0  1.000000  5.0   9  15.0
1  2.000000  6.5  10  14.0
2  2.333333  6.5  11  15.0
3  4.000000  8.0  12  16.0

In [35]:
values={
    'A': 0,'B': 100,'C': 200,'D':300}
df2.fillna(value=values)

     A      B   C      D
0  1.0    5.0   9  300.0
1  2.0  100.0  10   14.0
2  0.0  100.0  11   15.0
3  4.0    8.0  12   16.0

In [41]:
df1[df1['age']>18]

      name  age         city  salary
0    Alice   25     New York   70000
1      Bob   30  Los Angeles   80000
2  Charlie   35      Chicago   90000
3    David   40      Houston  100000

In [42]:
df1[df1['age']>18].loc[:,['name','age']]

      name  age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40

mergin and joining concatinations

In [54]:
import pandas as pd
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4],
    'name': ['Alice', 'Bob', 'Charlie', 'David'],
    'department': ['HR', 'Finance', 'IT', 'Marketing']})


salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 5],
    'salary': [70000, 80000, 90000, 100000],
    'bonus': [5000, 6000, 7000, 8000]})

In [48]:
employees

   emloyee_id     name department
0           1    Alice         HR
1           2      Bob    Finance
2           3  Charlie         IT
3           4    David  Marketing

In [50]:
salaries

   employee_id  salary  bonus
0            1   70000   5000
1            2   80000   6000
2            3   90000   7000
3            4  100000   8000

In [55]:
pd.merge(employees, salaries, on='employee_id')

   employee_id     name department  salary  bonus
0            1    Alice         HR   70000   5000
1            2      Bob    Finance   80000   6000
2            3  Charlie         IT   90000   7000

In [57]:
pd.merge(employees,salaries,on='employee_id',how='inner')

   employee_id     name department  salary  bonus
0            1    Alice         HR   70000   5000
1            2      Bob    Finance   80000   6000
2            3  Charlie         IT   90000   7000

In [58]:
pd.merge(employees,salaries,on='employee_id',how='outer')

   employee_id     name department    salary   bonus
0            1    Alice         HR   70000.0  5000.0
1            2      Bob    Finance   80000.0  6000.0
2            3  Charlie         IT   90000.0  7000.0
3            4    David  Marketing       NaN     NaN
4            5      NaN        NaN  100000.0  8000.0

concatination in pandas

grouped and aggregation in pnadas

In [67]:
data={
    'category': ['A', 'B', 'A', 'B', 'C'],
    'value': [10, 20, 30, 40, 50],
    'sales': [100, 200, 300, 400, 500],
    'quantity': [1, 2, 3, 4, 5],
    'store': ['Store1', 'Store2', 'Store1', 'Store2', 'Store3'],
    'date':['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04', '2023-01-05']
}

df3=pd.DataFrame(data)

In [60]:
df3

  category  value  sales  quantity        date
0        A     10    100         1  2023-01-01
1        B     20    200         2  2023-01-02
2        A     30    300         3  2023-01-03
3        B     40    400         4  2023-01-04
4        C     50    500         5  2023-01-05

In [65]:
cat=df3.groupby('category')['sales'].sum()
cat

category
A    400
B    600
C    500
Name: sales, dtype: int64

In [68]:
st=df3.groupby('store')['sales'].sum()
st

store
Store1    400
Store2    600
Store3    500
Name: sales, dtype: int64

In [69]:
df3.groupby(['category','store'])['sales'].sum()

category  store
A         Store1    400
B         Store2    600
C         Store3    500
Name: sales, dtype: int64

Aggregation

In [71]:
df3['sales'].mean()

np.float64(300.0)

In [74]:
df3['sales'].mode()

0    100
1    200
2    300
3    400
4    500
Name: sales, dtype: int64

In [ ]:
df3['sales'].std()
#std,min,max,mean,mode,

np.float64(158.11388300841898)

In [80]:
df3['sales'].agg(['sum', 'mean', 'max', 'min','std'])

sum     1500.000000
mean     300.000000
max      500.000000
min      100.000000
std      158.113883
Name: sales, dtype: float64

#Pivot Table

In [87]:
data3={
    'Date':pd.date_range(start='2023-01-01', periods=20,),
    'Product': ['A', 'B', 'C', 'D', 'E']*4,
    'Region':['North','East','South','West','Central','North','East','South','West','Central','North','East','South','West','Central','North','East','South','West','Central'],
    
    'Sales':np.random.randint(100, 500, size=20),
    'Units': np.random.randint(1, 10, size=20),
    'Rep':['Rep1', 'Rep2', 'Rep3', 'Rep4', 'Rep5', 'Rep1', 'Rep2', 'Rep3', 'Rep4', 'Rep5',
           'Rep1', 'Rep2', 'Rep3', 'Rep4', 'Rep5', 'Rep1', 'Rep2', 'Rep3', 'Rep4', 'Rep5']
}

df4=pd.DataFrame(data3)

df4['Month'] = df4['Date'].dt.month_name()
df4

         Date Product   Region  Sales  Units   Rep    Month
0  2023-01-01       A    North    335      4  Rep1  January
1  2023-01-02       B     East    480      7  Rep2  January
2  2023-01-03       C    South    383      9  Rep3  January
3  2023-01-04       D     West    202      7  Rep4  January
4  2023-01-05       E  Central    217      8  Rep5  January
5  2023-01-06       A    North    484      4  Rep1  January
6  2023-01-07       B     East    449      6  Rep2  January
7  2023-01-08       C    South    284      3  Rep3  January
8  2023-01-09       D     West    309      9  Rep4  January
9  2023-01-10       E  Central    383      9  Rep5  January
10 2023-01-11       A    North    146      1  Rep1  January
11 2023-01-12       B     East    193      6  Rep2  January
12 2023-01-13       C    South    364      3  Rep3  January
13 2023-01-14       D     West    438      3  Rep4  January
14 2023-01-15       E  Central    433      2  Rep5  January
15 2023-01-16       A    North    489      8  Rep1  January
16 2023-01-17       B     East    203      9  Rep2  January
17 2023-01-18       C    South    221      9  Rep3  January
18 2023-01-19       D     West    421      6  Rep4  January
19 2023-01-20       E  Central    413      4  Rep5  January

In [88]:
pd.pivot_table(df4,values='Sales', index=['Product', 'Region'], columns='Month', aggfunc='sum', fill_value=0)

Month            January
Product Region
A       North       1454
B       East        1325
C       South       1252
D       West        1370
E       Central     1446

Operation