pandas is  one of the most popular and widely used programming languages in the world. It is known for its simplicity, readability, and versatility, making it an excellent choice for both beginners and experienced developers.

types of pandas
sereis and dataframe

series
A series is  one dimensional labeled data

In [7]:
import pandas as pd
import numpy as np
label=['a','b','c','d']
my_list=[10,20,30,40]
arr=np.array([1,2,3,4,5,6])
d={'a':10,'b':20,'c':30,'d':40}
pd.Series(my_list )

0    10
1    20
2    30
3    40
dtype: int64

In [4]:
pd.Series(my_list,index=label)

a    10
b    20
c    30
d    40
dtype: int64

In [8]:
pd.Series(arr)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [9]:
pd.Series(d)

a    10
b    20
c    30
d    40
dtype: int64

DataFrame combined multiple series

Creating a dataframe
selection and indexing of columns
creating a new column
removing column 
selecting row 
selecting subsets of rows and column 
conditional selections

In [10]:
import pandas as pd
import numpy as np
data={
    'name':['Tom','Jerry','Mickey','Donald'],
    'age':[20,21,22,23],
    'city':['New York','Los Angeles','Chicago','Houston']  ,
    'salary':[50000,60000,70000,80000]
}

pd.DataFrame(data)

     name  age         city  salary
0     Tom   20     New York   50000
1   Jerry   21  Los Angeles   60000
2  Mickey   22      Chicago   70000
3  Donald   23      Houston   80000

In [13]:
data_list=[
    ['Tom',20,'New York',50000],['Jerry',21,'Los Angeles',60000],
    ['Mickey',22,'Chicago',70000],['Donald',23,'Houston',80000]]

df=pd.DataFrame(data_list,columns=['name','age','city','salary'])

In [14]:
df.head(5)

     name  age         city  salary
0     Tom   20     New York   50000
1   Jerry   21  Los Angeles   60000
2  Mickey   22      Chicago   70000
3  Donald   23      Houston   80000

selecting and indexing of columns

In [18]:
df['city']

0       New York
1    Los Angeles
2        Chicago
3        Houston
Name: city, dtype: object

In [19]:
df[['name','age']]

     name  age
0     Tom   20
1   Jerry   21
2  Mickey   22
3  Donald   23

creating new columns

In [20]:
df['Designation']=['Engineer','Doctor','Artist','Pilot']

In [21]:
df

     name  age         city  salary Designation
0     Tom   20     New York   50000    Engineer
1   Jerry   21  Los Angeles   60000      Doctor
2  Mickey   22      Chicago   70000      Artist
3  Donald   23      Houston   80000       Pilot

In [24]:
df.drop('Designation',axis=1,inplace=True)

In [25]:
df

     name  age         city  salary
0     Tom   20     New York   50000
1   Jerry   21  Los Angeles   60000
2  Mickey   22      Chicago   70000
3  Donald   23      Houston   80000

In [26]:
df.drop(0,axis=0)

     name  age         city  salary
1   Jerry   21  Los Angeles   60000
2  Mickey   22      Chicago   70000
3  Donald   23      Houston   80000

Selecting a rows

In [29]:
df.loc[[0,1]]

    name  age         city  salary
0    Tom   20     New York   50000
1  Jerry   21  Los Angeles   60000

selecting subsets of rows and columns

In [31]:
df.loc[[0,1],['name','age']]

    name  age
0    Tom   20
1  Jerry   21

conditional selecting

In [32]:
df[df['age']>21]

     name  age     city  salary
2  Mickey   22  Chicago   70000
3  Donald   23  Houston   80000

In [36]:
df[(df['age']>21 )& (df['city']=='Chicago')]

     name  age     city  salary
2  Mickey   22  Chicago   70000

Missing data  and finding null value

In [37]:
data={
    'A': [1, 2, np.nan, 4],
    'B': [5, np.nan, np.nan, 8],
    'C': [9, 10, 11, 12],
    'D': [np.nan, 14, 15, 16]
}

df = pd.DataFrame(data)

In [38]:
df

     A    B   C     D
0  1.0  5.0   9   NaN
1  2.0  NaN  10  14.0
2  NaN  NaN  11  15.0
3  4.0  8.0  12  16.0

In [39]:
df.isna()

       A      B      C      D
0  False  False  False   True
1  False   True  False  False
2   True   True  False  False
3  False  False  False  False

In [41]:
df.isnull().sum()

A    1
B    2
C    0
D    1
dtype: int64

removing null values

In [42]:
df.dropna()

     A    B   C     D
3  4.0  8.0  12  16.0

In [44]:
df.dropna(thresh=3)

     A    B   C     D
0  1.0  5.0   9   NaN
1  2.0  NaN  10  14.0
3  4.0  8.0  12  16.0

In [45]:
df.fillna(0)

     A    B   C     D
0  1.0  5.0   9   0.0
1  2.0  0.0  10  14.0
2  0.0  0.0  11  15.0
3  4.0  8.0  12  16.0

In [46]:
values={
    'A': 0,'B': 100,'C': 200,'D': 400}
df.fillna(value=values)

     A      B   C      D
0  1.0    5.0   9  400.0
1  2.0  100.0  10   14.0
2  0.0  100.0  11   15.0
3  4.0    8.0  12   16.0

In [47]:
df.fillna(df.mean())

          A    B   C     D
0  1.000000  5.0   9  15.0
1  2.000000  6.5  10  14.0
2  2.333333  6.5  11  15.0
3  4.000000  8.0  12  16.0